#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

// set is always zero, binding is always the same index as the buffer in the pipeline creation struct
layout(binding = 0) buffer Positions
{
    vec4 pos[];
} positions;

void main()
{
    vec2 current_pos = positions.pos[gl_GlobalInvocationID.x].xy;
    positions.pos[gl_GlobalInvocationID.x].xy = current_pos - vec2(1.0, 1.0);
}